version: "3.8"

services:
  dotnetbackend:
    build: ./dotnet-docker
    ports:
      - 3006:80
    expose:
      - "80"
    networks:
      - mynet
  nginx:
    build: ./vite-docker
    ports:
      - 3080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynet
    environment:
      NODE_ENV: production

networks:
  mynet:
    driver: bridge