version: "3.8"

services:
  react:
    build: ./vite-docker
    networks:
     - mynet
  dotnetbackend:
    build: ./dotnet-docker
    expose:
      - "80"
    networks:
      - mynet
    environment:
      jwt_key: ${token_key}
      cipher_key: ${encryption_key}
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/code.crt:/etc/nginx/ssl/code.crt:ro
      - ./nginx/ssl/code.key:/etc/nginx/ssl/code.key:ro
    networks:
      - mynet

networks:
  mynet:
    driver: bridge